<?php

namespace App\Enums;

enum Language: string
{
    case AB = 'ab'; // Abkhaze
    case AA = 'aa'; // Afar
    case AF = 'af'; // Afrikaans
    case AK = 'ak'; // Akan
    case SQ = 'sq'; // Albanais
    case AM = 'am'; // Amharique
    case AR = 'ar'; // Arabe
    case AN = 'an'; // Aragonais
    case HY = 'hy'; // Arménien
    case AS = 'as'; // Assamais
    case AV = 'av'; // Avar
    case AE = 'ae'; // Avestique
    case AY = 'ay'; // Aymara
    case AZ = 'az'; // Azéri
    case BM = 'bm'; // Bambara
    case BA = 'ba'; // Bachkir
    case EU = 'eu'; // Basque
    case BE = 'be'; // Biélorusse
    case BN = 'bn'; // Bengali
    case BH = 'bh'; // Bihari
    case BI = 'bi'; // Bichelamar
    case BS = 'bs'; // Bosniaque
    case BR = 'br'; // Breton
    case BG = 'bg'; // Bulgare
    case MY = 'my'; // Birman
    case CA = 'ca'; // Catalan
    case CH = 'ch'; // Chamorro
    case CE = 'ce'; // Tchétchène
    case NY = 'ny'; // Chichewa
    case ZH = 'zh'; // Chinois
    case CV = 'cv'; // Tchouvache
    case KW = 'kw'; // Cornique
    case CO = 'co'; // Corse
    case CR = 'cr'; // Cri
    case HR = 'hr'; // Croate
    case CS = 'cs'; // Tchèque
    case DA = 'da'; // Danois
    case DV = 'dv'; // Divehi
    case NL = 'nl'; // Néerlandais
    case DZ = 'dz'; // Dzongkha
    case EN = 'en'; // Anglais
    case EO = 'eo'; // Espéranto
    case ET = 'et'; // Estonien
    case EE = 'ee'; // Ewe
    case FO = 'fo'; // Féroïen
    case FJ = 'fj'; // Fidjien
    case FI = 'fi'; // Finnois
    case FR = 'fr'; // Français
    case FF = 'ff'; // Peul
    case GL = 'gl'; // Galicien
    case KA = 'ka'; // Géorgien
    case DE = 'de'; // Allemand
    case EL = 'el'; // Grec
    case GN = 'gn'; // Guarani
    case GU = 'gu'; // Gujarati
    case HT = 'ht'; // Haïtien
    case HA = 'ha'; // Haoussa
    case HE = 'he'; // Hébreu
    case HZ = 'hz'; // Héréro
    case HI = 'hi'; // Hindi
    case HO = 'ho'; // Hiri motu
    case HU = 'hu'; // Hongrois
    case IA = 'ia'; // Interlingua
    case ID = 'id'; // Indonésien
    case IE = 'ie'; // Occidental
    case GA = 'ga'; // Irlandais
    case IG = 'ig'; // Igbo
    case IK = 'ik'; // Inupiak
    case IO = 'io'; // Ido
    case IS = 'is'; // Islandais
    case IT = 'it'; // Italien
    case IU = 'iu'; // Inuktitut
    case JA = 'ja'; // Japonais
    case JV = 'jv'; // Javanais
    case KL = 'kl'; // Groenlandais
    case KN = 'kn'; // Kannada
    case KR = 'kr'; // Kanouri
    case KS = 'ks'; // Cachemiri
    case KK = 'kk'; // Kazakh
    case KM = 'km'; // Khmer
    case KI = 'ki'; // Kikuyu
    case RW = 'rw'; // Kinyarwanda
    case KY = 'ky'; // Kirghize
    case KV = 'kv'; // Komi
    case KG = 'kg'; // Kikongo
    case KO = 'ko'; // Coréen
    case KU = 'ku'; // Kurde
    case KJ = 'kj'; // Kuanyama
    case LA = 'la'; // Latin
    case LB = 'lb'; // Luxembourgeois
    case LG = 'lg'; // Ganda
    case LI = 'li'; // Limbourgeois
    case LN = 'ln'; // Lingala
    case LO = 'lo'; // Lao
    case LT = 'lt'; // Lituanien
    case LU = 'lu'; // Luba-katanga
    case LV = 'lv'; // Letton
    case GV = 'gv'; // Mannois
    case MK = 'mk'; // Macédonien
    case MG = 'mg'; // Malgache
    case MS = 'ms'; // Malais
    case ML = 'ml'; // Malayalam
    case MT = 'mt'; // Maltais
    case MI = 'mi'; // Maori
    case MR = 'mr'; // Marathi
    case MH = 'mh'; // Marshallais
    case MN = 'mn'; // Mongol
    case NA = 'na'; // Nauruan
    case NV = 'nv'; // Navajo
    case NB = 'nb'; // Norvégien bokmål
    case ND = 'nd'; // Ndébélé du Nord
    case NE = 'ne'; // Népalais
    case NG = 'ng'; // Ndonga
    case NN = 'nn'; // Norvégien nynorsk
    case NO = 'no'; // Norvégien
    case II = 'ii'; // Yi de Sichuan
    case NR = 'nr'; // Ndébélé du Sud
    case OC = 'oc'; // Occitan
    case OJ = 'oj'; // Ojibwé
    case CU = 'cu'; // Slavon d'église
    case OM = 'om'; // Oromo
    case OR = 'or'; // Oriya
    case OS = 'os'; // Ossète
    case PA = 'pa'; // Pendjabi
    case PI = 'pi'; // Pali
    case FA = 'fa'; // Persan
    case PL = 'pl'; // Polonais
    case PS = 'ps'; // Pachto
    case PT = 'pt'; // Portugais
    case QU = 'qu'; // Quechua
    case RM = 'rm'; // Romanche
    case RN = 'rn'; // Rundi
    case RO = 'ro'; // Roumain
    case RU = 'ru'; // Russe
    case SA = 'sa'; // Sanskrit
    case SC = 'sc'; // Sarde
    case SD = 'sd'; // Sindhi
    case SE = 'se'; // Same du Nord
    case SM = 'sm'; // Samoan
    case SG = 'sg'; // Sango
    case SR = 'sr'; // Serbe
    case GD = 'gd'; // Gaélique écossais
    case SN = 'sn'; // Shona
    case SI = 'si'; // Cingalais
    case SK = 'sk'; // Slovaque
    case SL = 'sl'; // Slovène
    case SO = 'so'; // Somali
    case ST = 'st'; // Sotho du Sud
    case ES = 'es'; // Espagnol
    case SU = 'su'; // Soundanais
    case SW = 'sw'; // Swahili
    case SS = 'ss'; // Swati
    case SV = 'sv'; // Suédois
    case TA = 'ta'; // Tamoul
    case TE = 'te'; // Télougou
    case TG = 'tg'; // Tadjik
    case TH = 'th'; // Thaï
    case TI = 'ti'; // Tigrigna
    case BO = 'bo'; // Tibétain
    case TK = 'tk'; // Turkmène
    case TL = 'tl'; // Tagalog
    case TN = 'tn'; // Tswana
    case TO = 'to'; // Tongien
    case TR = 'tr'; // Turc
    case TS = 'ts'; // Tsonga
    case TT = 'tt'; // Tatar
    case TW = 'tw'; // Twi
    case TY = 'ty'; // Tahitien
    case UG = 'ug'; // Ouïghour
    case UK = 'uk'; // Ukrainien
    case UR = 'ur'; // Ourdou
    case UZ = 'uz'; // Ouzbek
    case VE = 've'; // Venda
    case VI = 'vi'; // Vietnamien
    case VO = 'vo'; // Volapük
    case WA = 'wa'; // Wallon
    case CY = 'cy'; // Gallois
    case WO = 'wo'; // Wolof
    case FY = 'fy'; // Frison occidental
    case XH = 'xh'; // Xhosa
    case YI = 'yi'; // Yiddish
    case YO = 'yo'; // Yoruba
    case ZA = 'za'; // Zhuang
    case ZU = 'zu'; // Zoulou

    public function label(): string
    {
        return match ($this) {
            self::AB => 'Abkhaze',
            self::AA => 'Afar',
            self::AF => 'Afrikaans',
            self::AK => 'Akan',
            self::SQ => 'Albanais',
            self::AM => 'Amharique',
            self::AR => 'Arabe',
            self::AN => 'Aragonais',
            self::HY => 'Arménien',
            self::AS => 'Assamais',
            self::AV => 'Avar',
            self::AE => 'Avestique',
            self::AY => 'Aymara',
            self::AZ => 'Azéri',
            self::BM => 'Bambara',
            self::BA => 'Bachkir',
            self::EU => 'Basque',
            self::BE => 'Biélorusse',
            self::BN => 'Bengali',
            self::BH => 'Bihari',
            self::BI => 'Bichelamar',
            self::BS => 'Bosniaque',
            self::BR => 'Breton',
            self::BG => 'Bulgare',
            self::MY => 'Birman',
            self::CA => 'Catalan',
            self::CH => 'Chamorro',
            self::CE => 'Tchétchène',
            self::NY => 'Chichewa',
            self::ZH => 'Chinois',
            self::CV => 'Tchouvache',
            self::KW => 'Cornique',
            self::CO => 'Corse',
            self::CR => 'Cri',
            self::HR => 'Croate',
            self::CS => 'Tchèque',
            self::DA => 'Danois',
            self::DV => 'Divehi',
            self::NL => 'Néerlandais',
            self::DZ => 'Dzongkha',
            self::EN => 'Anglais',
            self::EO => 'Espéranto',
            self::ET => 'Estonien',
            self::EE => 'Ewe',
            self::FO => 'Féroïen',
            self::FJ => 'Fidjien',
            self::FI => 'Finnois',
            self::FR => 'Français',
            self::FF => 'Peul',
            self::GL => 'Galicien',
            self::KA => 'Géorgien',
            self::DE => 'Allemand',
            self::EL => 'Grec',
            self::GN => 'Guarani',
            self::GU => 'Gujarati',
            self::HT => 'Haïtien',
            self::HA => 'Haoussa',
            self::HE => 'Hébreu',
            self::HZ => 'Héréro',
            self::HI => 'Hindi',
            self::HO => 'Hiri motu',
            self::HU => 'Hongrois',
            self::IA => 'Interlingua',
            self::ID => 'Indonésien',
            self::IE => 'Occidental',
            self::GA => 'Irlandais',
            self::IG => 'Igbo',
            self::IK => 'Inupiak',
            self::IO => 'Ido',
            self::IS => 'Islandais',
            self::IT => 'Italien',
            self::IU => 'Inuktitut',
            self::JA => 'Japonais',
            self::JV => 'Javanais',
            self::KL => 'Groenlandais',
            self::KN => 'Kannada',
            self::KR => 'Kanouri',
            self::KS => 'Cachemiri',
            self::KK => 'Kazakh',
            self::KM => 'Khmer',
            self::KI => 'Kikuyu',
            self::RW => 'Kinyarwanda',
            self::KY => 'Kirghize',
            self::KV => 'Komi',
            self::KG => 'Kikongo',
            self::KO => 'Coréen',
            self::KU => 'Kurde',
            self::KJ => 'Kuanyama',
            self::LA => 'Latin',
            self::LB => 'Luxembourgeois',
            self::LG => 'Ganda',
            self::LI => 'Limbourgeois',
            self::LN => 'Lingala',
            self::LO => 'Lao',
            self::LT => 'Lituanien',
            self::LU => 'Luba-katanga',
            self::LV => 'Letton',
            self::GV => 'Mannois',
            self::MK => 'Macédonien',
            self::MG => 'Malgache',
            self::MS => 'Malais',
            self::ML => 'Malayalam',
            self::MT => 'Maltais',
            self::MI => 'Maori',
            self::MR => 'Marathi',
            self::MH => 'Marshallais',
            self::MN => 'Mongol',
            self::NA => 'Nauruan',
            self::NV => 'Navajo',
            self::NB => 'Norvégien bokmål',
            self::ND => 'Ndébélé du Nord',
            self::NE => 'Népalais',
            self::NG => 'Ndonga',
            self::NN => 'Norvégien nynorsk',
            self::NO => 'Norvégien',
            self::II => 'Yi de Sichuan',
            self::NR => 'Ndébélé du Sud',
            self::OC => 'Occitan',
            self::OJ => 'Ojibwé',
            self::CU => 'Slavon d\'église',
            self::OM => 'Oromo',
            self::OR => 'Oriya',
            self::OS => 'Ossète',
            self::PA => 'Pendjabi',
            self::PI => 'Pali',
            self::FA => 'Persan',
            self::PL => 'Polonais',
            self::PS => 'Pachto',
            self::PT => 'Portugais',
            self::QU => 'Quechua',
            self::RM => 'Romanche',
            self::RN => 'Rundi',
            self::RO => 'Roumain',
            self::RU => 'Russe',
            self::SA => 'Sanskrit',
            self::SC => 'Sarde',
            self::SD => 'Sindhi',
            self::SE => 'Same du Nord',
            self::SM => 'Samoan',
            self::SG => 'Sango',
            self::SR => 'Serbe',
            self::GD => 'Gaélique écossais',
            self::SN => 'Shona',
            self::SI => 'Cingalais',
            self::SK => 'Slovaque',
            self::SL => 'Slovène',
            self::SO => 'Somali',
            self::ST => 'Sotho du Sud',
            self::ES => 'Espagnol',
            self::SU => 'Soundanais',
            self::SW => 'Swahili',
            self::SS => 'Swati',
            self::SV => 'Suédois',
            self::TA => 'Tamoul',
            self::TE => 'Télougou',
            self::TG => 'Tadjik',
            self::TH => 'Thaï',
            self::TI => 'Tigrigna',
            self::BO => 'Tibétain',
            self::TK => 'Turkmène',
            self::TL => 'Tagalog',
            self::TN => 'Tswana',
            self::TO => 'Tongien',
            self::TR => 'Turc',
            self::TS => 'Tsonga',
            self::TT => 'Tatar',
            self::TW => 'Twi',
            self::TY => 'Tahitien',
            self::UG => 'Ouïghour',
            self::UK => 'Ukrainien',
            self::UR => 'Ourdou',
            self::UZ => 'Ouzbek',
            self::VE => 'Venda',
            self::VI => 'Vietnamien',
            self::VO => 'Volapük',
            self::WA => 'Wallon',
            self::CY => 'Gallois',
            self::WO => 'Wolof',
            self::FY => 'Frison occidental',
            self::XH => 'Xhosa',
            self::YI => 'Yiddish',
            self::YO => 'Yoruba',
            self::ZA => 'Zhuang',
            self::ZU => 'Zoulou',

        };
    }
    public function tagColorVariable(): string
    {
        return '--color-tag-language';
    }
}
